version: "2.1"
services:
  airsonic:
    image: airsonic/airsonic:latest
    container_name: airsonic-dc
    environment:
      - PUID=1000
      - PGID=audio
        #- PGID=1000
      - HOME=/config
      - TZ=Asia/Seoul
        #      - CONTEXT_PATH=<URL_BASE> #optional
        #      - JAVA_OPTS=server.forward-headers-strategy=native #optional
    volumes:
      - ./airsonic/config:/config
      - ./airsonic/sound.properties:/usr/lib/jvm/java-1.8-openjdk/jre/lib/sound.properties
      - ./airsonic/music:/airsonic/music:ro
      - ./airsonic/playlist:/playlists
      - ./airsonic/podcasts:/podcasts
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
